### ISSUE TITLE
Adding Google search html code to modals

### ISSUE THREAD

**Issue by tooraje** [sethmacleod/dimension#18]
I am trying to add a google search code like this:

```
<div>
<script>
  (function() {
    var cx = '006389791431410470787:s9zotyq0r7m';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
</div>
```
to a modal (pages that their URL starts with #, for example: www.mywebsite.com/#page1). But it does not work by just copy the above code to the **page1.md**
How can I do that?

**Comment by sethmacleod** [comment]
I just did a quick test. I got the search box to display by using the settings from the Google docs example. The [document](https://developers.google.com/custom-search/docs/tutorial/implementingsearchbox) and the [example](http://jsfiddle.net/gh/gist/library/pure/6130833/).

I used the same format as your example:

```
<div>
<script>
// Make sure in jsFiddle you have selected option onLoad
(function() {
  var cx = '017643444788069204610:4gvhea_mvga'; // Insert your own Custom Search engine ID here
  var gcse = document.createElement('script'); gcse.type = 'text/javascript'; gcse.async = true;
  gcse.src = (document.location.protocol == 'https' ? 'https:' : 'http:') +
      '//www.google.com/cse/cse.js?cx=' + cx;
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(gcse, s);
})();
</script>
<gcse:search></gcse:search>
</div>
```

Check to make sure that you have your CSE set up correctly.
