### ISSUE TITLE
Problem with Dimension Theme Ft. Hugo Easy Gallery

### ISSUE THREAD

**Issue by TheDudeBMF** [sethmacleod/dimension#27]
I’m implementing the Hugo Easy Gallery on my site but I have a problem with it in combination with the Dimension theme.

I run the gallery on this page: http://newsite.luckycharmtattoo.nl/#portfolio
When I click one of the images, the gallery doesn’t go full screen, but it seems ‘caputered’ in the underlaying layer of the theme. 
![Screenshot](https://user-images.githubusercontent.com/35812333/35402026-8efd6b76-01fb-11e8-9c57-a10c49b58a26.png)

Because of this, the gallery doesn’t go to the center of the display and doesn’t scale. Does someone know how I can avoid this so the gallery works as good as on the[ authors website](https://www.liwen.id.au/heg/)?

**Comment by balgarath** [comment]
Having the same problem, did you ever figure it out?

**Comment by TheDudeBMF** [comment]
I found a work around. The ‘solution’ is that I use a javascript gallery. See luckycharmtattoo.nl
