### ISSUE TITLE
Adding link to other page in menu

### ISSUE THREAD

**Issue by kertase** [sethmacleod/dimension#4]
Hi,

Is it possible to add a link to an other page in the menu?

Thanks

**Comment by sethmacleod** [comment]
Do you mean link to a page like `example.org/page` instead of using `example.org/#page` which would use the modal?

**Comment by kertase** [comment]
Yes, or else also to an external page like example2.org

**Comment by kertase** [comment]
Great thanks a lot for this theme and you help.
