### ISSUE TITLE
 sass link to wrong forlderfor background image and link relative to css/scss file 

### ISSUE THREAD

**Issue by kertase** [sethmacleod/dimension#8]
Hi,

I noticed that the bg.jpg is linked wrongly at:
https://github.com/sethmacleod/dimension/blob/91a339641028cd2251ca925d6a88f8471aa1247a/static/sass/layout/_bg.scss#L33

Also it seams weird that the bg.img is not linked relative to the root of the website.
https://github.com/sethmacleod/dimension/blob/c184bc3aec9b491186e139360e0c8d804603e8cd/static/css/main.css#L1094
but maybe that is wanted like that?

Greets

**Comment by sethmacleod** [comment]
Ah, so I have a confession to make: I didn't have Sass set up on my laptop at the time, so I just made a couple of quick changes to the css files thinking that no one would notice and if they did, then they knew how to use Sass anyway!

I'll fix it soon 😆 

Re: linking, I'll fix it when I correct the Sass.
